### ISSUE TITLE
Unclear and non-updated add-namespace bin file

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3465]
### Description

Using the latest recommended version, when adding a namespace, you get the error

```shell
➜  shellhub git:(v0.13.1) ✗  ./bin/add-namespace test.example.org seluj78

WARN[0000] The "SHELLHUB_TELEMETRY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SHELLHUB_TELEMETRY_SCHEDULE" variable is not set. Defaulting to a blank string.
WARN[0000] The "SHELLLHUB_ANNOUNCEMENTS" variable is not set. Defaulting to a blank string.
INFO[0000] Setting log level                             log_level=info
Command "add-namespace" is deprecated, This command is deprecated and will be removed in a future release. Please use 'cli namespace create' instead.
Error: namespace is invalid
Usage:
  cli add-namespace [flags]

Flags:
  -h, --help   help for add-namespace

ERRO[0000] namespace is invalid
```

Indeed, a domain name is an invalid namespace. In your [documentation](https://docs.shellhub.io/self-hosted/administration), you refer to a RFC which is very unclear. That's the first problem

Also, you can see a recommendation to use a `cli namespace create`

When running this, I get

```shell
➜  shellhub git:(v0.13.1) ✗ docker compose exec cli ./cli namespace create
WARN[0000] The "SHELLHUB_TELEMETRY" variable is not set. Defaulting to a blank string.
WARN[0000] The "SHELLHUB_TELEMETRY_SCHEDULE" variable is not set. Defaulting to a blank string.
WARN[0000] The "SHELLLHUB_ANNOUNCEMENTS" variable is not set. Defaulting to a blank string.
INFO[0000] Setting log level                             log_level=info
Error: accepts between 2 and 3 arg(s), received 0
Usage:
  cli namespace create <namespace> <owner> [tenant] [flags]

Examples:
cli namespace create dev john_doe

Flags:
  -h, --help   help for create

ERRO[0000] accepts between 2 and 3 arg(s), received 0
```

Which is already much clearer and explains that a namespace is just a string, so I was able to create the namespace that way

This bug report is task for an update on the documentation and the `create-namespace` script

### Edition

Community

### Version

0.13.1

**Comment by heiytor** [comment]
Hi, @Seluj78,

We acknowledge and agree with your observation regarding the documentation's lack of clarity on this matter. We've transitioned to the new `cli` script, which performs significantly better than the old scripts. I'm currently working on updating the documentation to incorporate the use of the new scripts.

Concerning the namespace's name, Shellhub expects an RFC1123 standard hostname, as indicated by the struct below:
```go
type NamespaceCreate struct {
    Namespace string `validate:"required,hostname_rfc1123,excludes=.,lowercase"`
    Owner     string `validate:"required,username"`
    TenantID  string `validate:"omitempty,uuid"`
}
```
The issue with your error is that the hostname cannot contain dots; removing it should resolve the problem.

As for your PR, we're uncertain about merging it because getting this deprecated script to run the new `cli` would require similar changes to everything else. This could potentially introduce a considerable number of backwards compatibility issues, which is why we chose to create new scripts.

If you have any questions, here is how to use all maintened scripts:
- `bin/cli user create` - create a new user
- `bin/cli user delete` - delete an existing user
- `bin/cli user password` - reset the user's password
- `bin/cli namespace create` - create a new namespace
- `bin/cli namespace delete` - delete an existing namespace
- `bin/cli namespace member add` - add a new member to the namespace
- `bin/cli namespace member remove` - remove an existing member from the namespace

**Comment by Seluj78** [comment]
Right thank you very much.

The question is, is the `bin/` folder going to be deleted in favor of your new cli ?

**Comment by heiytor** [comment]
The deprecated scripts will be deleted in the future, but the `bin` folder will remain intact. For that reason, I strongly recommend using only `bin/cli`.

**Comment by Seluj78** [comment]
Oh right ok got it. Just missing the documentation update then ;)

**Comment by heiytor** [comment]
Done! :)
