### ISSUE TITLE
What timezone is used by the return from the API

### ISSUE THREAD

**Issue by Seluj78** [shellhub-io/shellhub#3524]
### Description

Question is the title :) See https://github.com/Seluj78/shellhub-python/pull/10#discussion_r1481852110 for details of why I'm asking this :)

### Edition

Community

### Version

0.14.1

**Comment by heiytor** [comment]
Hi, @Seluj78.

We utilize a package called clock, which abstracts the logic related to time. This package includes a [Now](https://github.com/shellhub-io/shellhub/blob/master/pkg/clock/clock.go#L28-L30) method that utilizes the local timezone of the host machine. However, since ShellHub runs inside a Docker container and the default timezone is UTC-0, I am quite certain that your instance is using this timezone.

**Comment by Seluj78** [comment]
Great, thank you for the quick answer, I'll make sure to explain that in the PR :)
